// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuditEvent = `-- name: CreateAuditEvent :exec
INSERT INTO audit_events (
    document_id, event_type, message, actor_type, actor_user_id, actor_signer_id, actor_label
) VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateAuditEventParams struct {
	DocumentID    pgtype.UUID `json:"document_id"`
	EventType     string      `json:"event_type"`
	Message       string      `json:"message"`
	ActorType     string      `json:"actor_type"`
	ActorUserID   pgtype.UUID `json:"actor_user_id"`
	ActorSignerID pgtype.UUID `json:"actor_signer_id"`
	ActorLabel    string      `json:"actor_label"`
}

func (q *Queries) CreateAuditEvent(ctx context.Context, arg CreateAuditEventParams) error {
	_, err := q.db.Exec(ctx, createAuditEvent,
		arg.DocumentID,
		arg.EventType,
		arg.Message,
		arg.ActorType,
		arg.ActorUserID,
		arg.ActorSignerID,
		arg.ActorLabel,
	)
	return err
}

const listAuditEventsByDocument = `-- name: ListAuditEventsByDocument :many
SELECT seq, id, document_id, event_type, message, actor_type, actor_user_id, actor_signer_id, actor_label, created_at FROM audit_events WHERE document_id = $1 ORDER BY seq
`

func (q *Queries) ListAuditEventsByDocument(ctx context.Context, documentID pgtype.UUID) ([]AuditEvent, error) {
	rows, err := q.db.Query(ctx, listAuditEventsByDocument, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditEvent{}
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.Seq,
			&i.ID,
			&i.DocumentID,
			&i.EventType,
			&i.Message,
			&i.ActorType,
			&i.ActorUserID,
			&i.ActorSignerID,
			&i.ActorLabel,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
