// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: documents.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDocument = `-- name: CreateDocument :one
INSERT INTO documents (owner_id, filename, content_type, size, file_hash, storage_key)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, owner_id, filename, content_type, size, file_hash, storage_key, status, created_at
`

type CreateDocumentParams struct {
	OwnerID     pgtype.UUID `json:"owner_id"`
	Filename    string      `json:"filename"`
	ContentType string      `json:"content_type"`
	Size        int64       `json:"size"`
	FileHash    string      `json:"file_hash"`
	StorageKey  string      `json:"storage_key"`
}

func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, createDocument,
		arg.OwnerID,
		arg.Filename,
		arg.ContentType,
		arg.Size,
		arg.FileHash,
		arg.StorageKey,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Filename,
		&i.ContentType,
		&i.Size,
		&i.FileHash,
		&i.StorageKey,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const deleteDraftDocument = `-- name: DeleteDraftDocument :execrows
DELETE FROM documents
WHERE id = $1 AND owner_id = $2 AND status = 'draft'
`

type DeleteDraftDocumentParams struct {
	ID      pgtype.UUID `json:"id"`
	OwnerID pgtype.UUID `json:"owner_id"`
}

// Deletes only if the caller owns it AND it is still a draft. Returns the number
// of rows affected so the handler can tell "deleted" from "not allowed".
func (q *Queries) DeleteDraftDocument(ctx context.Context, arg DeleteDraftDocumentParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDraftDocument, arg.ID, arg.OwnerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getDocumentForOwner = `-- name: GetDocumentForOwner :one
SELECT id, owner_id, filename, content_type, size, file_hash, storage_key, status, created_at FROM documents
WHERE id = $1 AND owner_id = $2
`

type GetDocumentForOwnerParams struct {
	ID      pgtype.UUID `json:"id"`
	OwnerID pgtype.UUID `json:"owner_id"`
}

// Owner-scoped read: returns nothing if the document belongs to someone else,
// so authorization is enforced in the query, not just the handler.
func (q *Queries) GetDocumentForOwner(ctx context.Context, arg GetDocumentForOwnerParams) (Document, error) {
	row := q.db.QueryRow(ctx, getDocumentForOwner, arg.ID, arg.OwnerID)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Filename,
		&i.ContentType,
		&i.Size,
		&i.FileHash,
		&i.StorageKey,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listDocumentsByOwner = `-- name: ListDocumentsByOwner :many
SELECT id, owner_id, filename, content_type, size, file_hash, storage_key, status, created_at FROM documents
WHERE owner_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListDocumentsByOwner(ctx context.Context, ownerID pgtype.UUID) ([]Document, error) {
	rows, err := q.db.Query(ctx, listDocumentsByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Document{}
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Filename,
			&i.ContentType,
			&i.Size,
			&i.FileHash,
			&i.StorageKey,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
