// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditEvent struct {
	Seq           *int64             `json:"seq"`
	ID            pgtype.UUID        `json:"id"`
	DocumentID    pgtype.UUID        `json:"document_id"`
	EventType     string             `json:"event_type"`
	Message       string             `json:"message"`
	ActorType     string             `json:"actor_type"`
	ActorUserID   pgtype.UUID        `json:"actor_user_id"`
	ActorSignerID pgtype.UUID        `json:"actor_signer_id"`
	ActorLabel    string             `json:"actor_label"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type Document struct {
	ID          pgtype.UUID        `json:"id"`
	OwnerID     pgtype.UUID        `json:"owner_id"`
	Filename    string             `json:"filename"`
	ContentType string             `json:"content_type"`
	Size        int64              `json:"size"`
	FileHash    string             `json:"file_hash"`
	StorageKey  string             `json:"storage_key"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type PasswordResetToken struct {
	ID        pgtype.UUID        `json:"id"`
	TokenHash string             `json:"token_hash"`
	UserID    pgtype.UUID        `json:"user_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
}

type Session struct {
	ID        pgtype.UUID        `json:"id"`
	TokenHash string             `json:"token_hash"`
	UserID    pgtype.UUID        `json:"user_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

type Signer struct {
	ID            pgtype.UUID        `json:"id"`
	DocumentID    pgtype.UUID        `json:"document_id"`
	Email         string             `json:"email"`
	TokenHash     string             `json:"token_hash"`
	Status        string             `json:"status"`
	SignedName    *string            `json:"signed_name"`
	SignedAt      pgtype.Timestamptz `json:"signed_at"`
	SignedDocHash *string            `json:"signed_doc_hash"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}
