// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: signers.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPendingSigners = `-- name: CountPendingSigners :one
SELECT count(*) FROM signers WHERE document_id = $1 AND status = 'pending'
`

func (q *Queries) CountPendingSigners(ctx context.Context, documentID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingSigners, documentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSigner = `-- name: CreateSigner :one
INSERT INTO signers (document_id, email, token_hash, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, document_id, email, token_hash, status, signed_name, signed_at, signed_doc_hash, expires_at, created_at
`

type CreateSignerParams struct {
	DocumentID pgtype.UUID        `json:"document_id"`
	Email      string             `json:"email"`
	TokenHash  string             `json:"token_hash"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateSigner(ctx context.Context, arg CreateSignerParams) (Signer, error) {
	row := q.db.QueryRow(ctx, createSigner,
		arg.DocumentID,
		arg.Email,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var i Signer
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.Email,
		&i.TokenHash,
		&i.Status,
		&i.SignedName,
		&i.SignedAt,
		&i.SignedDocHash,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSignerByToken = `-- name: GetSignerByToken :one
SELECT id, document_id, email, token_hash, status, signed_name, signed_at, signed_doc_hash, expires_at, created_at FROM signers WHERE token_hash = $1
`

// The token hash is the only key a signer presents. Unique, so it maps to
// exactly one signer row — no signer can reach another's row or document.
func (q *Queries) GetSignerByToken(ctx context.Context, tokenHash string) (Signer, error) {
	row := q.db.QueryRow(ctx, getSignerByToken, tokenHash)
	var i Signer
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.Email,
		&i.TokenHash,
		&i.Status,
		&i.SignedName,
		&i.SignedAt,
		&i.SignedDocHash,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const listSignersByDocument = `-- name: ListSignersByDocument :many
SELECT id, document_id, email, token_hash, status, signed_name, signed_at, signed_doc_hash, expires_at, created_at FROM signers WHERE document_id = $1 ORDER BY created_at
`

func (q *Queries) ListSignersByDocument(ctx context.Context, documentID pgtype.UUID) ([]Signer, error) {
	rows, err := q.db.Query(ctx, listSignersByDocument, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Signer{}
	for rows.Next() {
		var i Signer
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.Email,
			&i.TokenHash,
			&i.Status,
			&i.SignedName,
			&i.SignedAt,
			&i.SignedDocHash,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const signSigner = `-- name: SignSigner :execrows
UPDATE signers
SET status = 'signed', signed_name = $2, signed_at = now(), signed_doc_hash = $3
WHERE id = $1 AND status = 'pending'
`

type SignSignerParams struct {
	ID            pgtype.UUID `json:"id"`
	SignedName    *string     `json:"signed_name"`
	SignedDocHash *string     `json:"signed_doc_hash"`
}

// Records the signature, but only if still pending. The status='pending' guard
// makes signing single-use: a spent token updates zero rows.
func (q *Queries) SignSigner(ctx context.Context, arg SignSignerParams) (int64, error) {
	result, err := q.db.Exec(ctx, signSigner, arg.ID, arg.SignedName, arg.SignedDocHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
